name: wait-for-workflows

on:
  pull_request:

jobs:
  required:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: int128/wait-for-workflows-action@v1
        with:
          filter-workflow-names: |
            Tests